// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("a65263f6-6bec-47de-a5c5-9956e2911e33")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("FixMe.Tests")]
